name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site into docs folder
        run: |
          bundle exec jekyll build --destination docs

      - name: Commit and push docs to gh-pages branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Site rebuilt by GitHub Actions"
          add: 'docs'
          branch: gh-pages
